services:
  app:
    image: mrras/code-observer:0.5.0
    container_name: code-observer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/app.db
    restart: unless-stopped