services:
  app:
    image: mrras/codebase-observer:0.2.0
    container_name: codebase-observer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/app.db
    restart: unless-stopped