name: Release Server

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-setup

      - name: Build web app
        run: ./gradlew :web:wasmJsBrowserDistribution

      - name: Build server
        run: ./gradlew :server:shadowJar

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t mrras/code-observer:${{ github.event.inputs.versionTag }} .

      - name: Push image
        run: docker push mrras/code-observer:${{ github.event.inputs.versionTag }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.versionTag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true